<?php

/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management.
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class AuditsController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation postGetAuditDocument
     *
     * Get Audit Document.
     *
     *
     * @return Http response
     */
    public function postGetAuditDocument()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['contentType'])) {
            throw new \InvalidArgumentException('Missing the required parameter $contentType when calling postGetAuditDocument');
        }
        $contentType = $input['contentType'];

        $getAuditDocumentRequest = $input['getAuditDocumentRequest'];


        return response('How about implementing postGetAuditDocument as a post method ?');
    }
    /**
     * Operation postGetDocumentAudit
     *
     * Get Document Audit.
     *
     *
     * @return Http response
     */
    public function postGetDocumentAudit()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['contentType'])) {
            throw new \InvalidArgumentException('Missing the required parameter $contentType when calling postGetDocumentAudit');
        }
        $contentType = $input['contentType'];

        $getDocumentAuditRequest = $input['getDocumentAuditRequest'];


        return response('How about implementing postGetDocumentAudit as a post method ?');
    }
}
