<?php

/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management.
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class SigningCeremonyController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation postMultipleSignersSigningCeremony
     *
     * Multiple Signers Signing Ceremony.
     *
     *
     * @return Http response
     */
    public function postMultipleSignersSigningCeremony()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['contentType'])) {
            throw new \InvalidArgumentException('Missing the required parameter $contentType when calling postMultipleSignersSigningCeremony');
        }
        $contentType = $input['contentType'];

        $multipleSignersSigningCeremonyRequest = $input['multipleSignersSigningCeremonyRequest'];


        return response('How about implementing postMultipleSignersSigningCeremony as a post method ?');
    }
    /**
     * Operation postSigningCeremonyV2
     *
     * Signing Ceremony V2.
     *
     *
     * @return Http response
     */
    public function postSigningCeremonyV2()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['contentType'])) {
            throw new \InvalidArgumentException('Missing the required parameter $contentType when calling postSigningCeremonyV2');
        }
        $contentType = $input['contentType'];

        $signingCeremonyV2Request = $input['signingCeremonyV2Request'];


        return response('How about implementing postSigningCeremonyV2 as a post method ?');
    }
}
