<?php

/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management.
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class ViewersController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation postGetDocLink
     *
     * Get Document Link.
     *
     *
     * @return Http response
     */
    public function postGetDocLink()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['contentType'])) {
            throw new \InvalidArgumentException('Missing the required parameter $contentType when calling postGetDocLink');
        }
        $contentType = $input['contentType'];

        $getDocLinkRequest = $input['getDocLinkRequest'];


        return response('How about implementing postGetDocLink as a post method ?');
    }
    /**
     * Operation postGetDocumentPrepperLink
     *
     * Get Document Prepper Link.
     *
     *
     * @return Http response
     */
    public function postGetDocumentPrepperLink()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['contentType'])) {
            throw new \InvalidArgumentException('Missing the required parameter $contentType when calling postGetDocumentPrepperLink');
        }
        $contentType = $input['contentType'];

        $getDocumentPrepperLinkRequest = $input['getDocumentPrepperLinkRequest'];


        return response('How about implementing postGetDocumentPrepperLink as a post method ?');
    }
}
