<?php
/**
 * GetDocumentRequest
 */
namespace SigniFlowConnect\Model;

/**
 * GetDocumentRequest
 */
class GetDocumentRequest {

    /** @var float $docIDField Document ID generated by SigniFlow.*/
    private $docIDField;

    /** @var \SigniFlowConnect\Model\TokenField $tokenField */
    private $tokenField;

}
